---
-
 hosts: myservers
 tasks:
         - name: Installing the HTTPD package.
           yum:
                   name: httpd
                   state: latest
           when: ansible_distribution == "RedHat"  and ansible_distribution_version == "8.3" 
...
