---
- 
  hosts: myservers
  tasks:
          - name: Copying files to the managed hosts
            copy:
              src: ./file.txt
              dest: /tmp
              force: yes
          - name: Add line in file.
            blockinfile:
                    path: /tmp/file.txt
                    block: |
                            I am adding this new block
                            This is a new block to show the test
                            This is the third line in this block
                    state: present
...
