---
- 
  hosts: myservers
  gather_facts: no
  tasks:
          - name: Running multiple commands in loop.
            command: "{{item}}"
            loop:
                    - "ls -la /tmp"
                    - "lsblk -fp"
            register: output

          - name: Printing the output
            debug:
                    msg: >  
                      - NBS*********************************************
                      - NBS message is "{{item.item}}"
                      - NBS message is "{{item.rc}}"
                      - NBS message is "{{item.stdout_lines}}"
                      - NBS*********************************************
            loop: "{{output['results']}}"

...
